### ISSUE TITLE
🇩🇪 Add German translation

### ISSUE THREAD

**Issue by stefanobartoletti** [stefanobartoletti/bricks#111]
🇩🇪 A German translation should be added 🇩🇪

To contribute, follow these simple rules:

- The translation should be located inside the `/languages` folder and created/edited with [Poedit](https://poedit.net/). 
- The translation file should be named `de_DE.po` and created by starting from the `template.pot` template.
- Poedit should be set to automatically create `.mo` file.
- You can use the already present italian translation as an example for your work.
- The translation should be made by a native or fluent speaker of the said language, not by using automated online tools like Google Translate or similar (I could do this myself, I'm looking for a more tailored contribution).
- Before translating strings, make sure to check the context where they will be displayed. After your translation work, run the local development environment to check if they are correct and make sense in-place (detailed installation instructions are available in the [Docs](https://bricks.stefanobartoletti.it/theme/))
- Ideally, the creator of a new translation should keep it updated also in future versions of Bricks (this is not required but strongly recommended. It should be a manageable task, it is not a lot of work).

🏵️ Thank you for your contribution and happy Hacktoberfest! 🏵️

**Comment by m1ga** [comment]
Would be happy to help here! Native :de: speaker

**Comment by m1ga** [comment]
already done, hope it's fine for you that I've started already #115

**Comment by stefanobartoletti** [comment]
Thank you!
I'm going to check it ASAP and merge it. 

Would you be interested in keeping the translation updated even in future versions of Bricks? (I don't usually make new releases very often, a new version ever month at most, and usually not every update modifies translations).

**Comment by m1ga** [comment]
I've stared the repo and have a look from time to time :+1:
