### ISSUE TITLE
custom SVG sprite without font awesome

### ISSUE THREAD

**Issue by bartdenhartog** [stefanobartoletti/bricks#154]
Hi,

I'm developing a new website on bricks, works fantastic but I was wondering how I can add a gulp task for a custom SVG icons sprite. Is it possible you could help me with this?

**Comment by stefanobartoletti** [comment]
Hi, first of all thanks for your interest in my theme.

Can you be more specific with your request? What exactly are you trying to do with this new task?

**Comment by bartdenhartog** [comment]
Hi, 

Thank you for your response. In an older theme is used the following gulp plugins so I could add custom SVG icons to my files:

gulp-svgstore
gulp-svgmin
gulp-cheerio

with the following task:

// Task: icons
gulp.task('icons', function() {
  return gulp.src('./assets/icons/svg/*')
    .pipe(svgmin())
    .pipe(svgstore({
      fileName: 'sprite.svg',
      inlineSvg: true
    }))
    .pipe(cheerio({
      run: function ($, file) {
          $('svg').addClass('hide')
          $('[fill]').removeAttr('fill')
      },
      parserOptions: { xmlMode: true }
    }))
    .pipe(rename('sprite.svg'))
    .pipe(gulp.dest('./assets/icons/'));
});

If I needed an icon in my file I added this:

<svg class="icon"><use xlink:href="#icon-chevron-right" /></svg>

I was wondering in which theme file of bricks I can add these tasks and plugins.

Thanks!

**Comment by stefanobartoletti** [comment]
Ok, you should put your own custom tasks inside `gulpfile.mjs` on the theme root folder.

Please note that tasks are defined with Gulp 4 syntax, so you may need to modify your own accordingly

**Comment by bartdenhartog** [comment]
Thank you, I'm gonna try it!
