### ISSUE TITLE
Font awesome not compile well.

### ISSUE THREAD

**Issue by khoipro** [stefanobartoletti/bricks#171]
I tried to setup a project with your base, however the latest font awesome compile which loads dist/js/fa5.min.js seems not working well. The icon is not render.

Have any tip?

**Comment by stefanobartoletti** [comment]
Hi, can you explain your issue more precisely? It is not very clear what you are asking, if you can give more details it would be better.

You can also read about this feature in the docs: https://bricks.stefanobartoletti.it/theme/icons/
