### ISSUE TITLE
Some Bootstrap classes not render well in npm run build

### ISSUE THREAD

**Issue by khoipro** [stefanobartoletti/bricks#174]
I tried to run a script with npm run build, and sometimes the final assets doesn't contain all Bootstrap classes, such as col-6, col-md-x, alert-info...

**Comment by stefanobartoletti** [comment]
Hi, thank you for your feedback.

I need a more precise report of what you are experiencing, and how to reproduce the problem. Without detailed information, it is impossible for me to provide help.
