### ISSUE TITLE
Sidebar for woocommerce

### ISSUE THREAD

**Issue by codeweberdotcom** [stefanobartoletti/bricks#262]
Hello Stefano!
First of all, I want to thank you for a wonderful build.

I have a question.
Now I'm working on Sidebar for woocommerce.
How to do it right?
Also the question is how to display any other sidebar for a particular Custom Post type ?

**Comment by codeweberdotcom** [comment]
______________________________________________________________________________________________________________________________
I created the sidebars >>>

`<?php

/**
 * https://developer.wordpress.org/themes/functionality/sidebars/
 */

if (!function_exists('brk_sidebars')) {

	function brk_sidebars()
	{

		register_sidebar(
			array(
				'name' => esc_html__('Main Sidebar', 'zinoviev-school'),
				'id' => 'sidebar-main',
				'description' => esc_html__('Main Sidebar', 'zinoviev-school'),
				'before_widget' => '<div class="widget mb-4 %2$s clearfix">',
				'after_widget' => '</div>',
				'before_title' => '<h3 class="mb-4">',
				'after_title' => '</h3>',
			)
		);
		register_sidebar(
			array(
				'name' => esc_html__('Woo Sidebar', 'zinoviev-school'),
				'id' => 'sidebar-woo',
				'description' => esc_html__('Woo Sidebar', 'zinoviev-school'),
				'before_widget' => '<div class="widget mb-4 %2$s clearfix">',
				'after_widget' => '</div>',
				'before_title' => '<h3 class="mb-4">',
				'after_title' => '</h3>',
			)
		);
		register_sidebar(
			array(
				'name' => esc_html__('Testimonials Sidebar', 'zinoviev-school'),
				'id' => 'sidebar-testimonials',
				'description' => esc_html__('Testimonials Sidebar', 'zinoviev-school'),
				'before_widget' => '<div class="widget mb-4 %2$s clearfix">',
				'after_widget' => '</div>',
				'before_title' => '<h3 class="mb-4">',
				'after_title' => '</h3>',
			)
		);
	}
}

add_action('widgets_init', 'brk_sidebars');`

_________________________________________________________________________________________________________________________________
I managed to display the sidebar by condition in CPT. >>>

`<aside id="sidebar-main-wrapper" class="col-sm-4 mt-5 mt-md-0 ps-md-5">

	<?php

	function is_post_type($type)
	{
		global $wp_query;
		if ($type == get_post_type($wp_query->post->ID))
			return true;
		return false;
	}
	?>

	<?php
	if (is_woocommerce() || is_shop()) {
		dynamic_sidebar('sidebar-woo');
	} elseif (is_archive('testimonials') || is_singular('testimonials')) {
		dynamic_sidebar('sidebar-testimonials');
	} else {
		dynamic_sidebar('sidebar-main');
	}
	?>

</aside> `


___________________________________________________________________________________________________________________________________

The problem remains with the Sidebar for the Shop page and the Shop category page.
In the product, my custom sidebar is displayed

Shop - sidebar not showing
Category - sidebar not showing
Product - sidebar is displayed

Help me please.

**Comment by stefanobartoletti** [comment]
I think that you need to call the specific sidebar from inside your templates.
Following the [documentation](https://developer.wordpress.org/themes/functionality/sidebars/), you should add a sidebar template called in example `sidebar-product.php`, and inside you product template file, calling it with `get_sidebar( 'product' )`, or by using a hook if necessary.

This is how WordPress sidebars work, there is not a special implementation used in Bricks, it uses the standard WordPress way.
