### ISSUE TITLE
Font Awesome Issue after Yarn Build

### ISSUE THREAD

**Issue by Westernwindscorp** [stefanobartoletti/bricks#280]
Hi Stefano,

I came across an issues that when ever I compiles all resources for a production environment using the "yarn build" command, the fontawesome.min.js file doesnt have some of the icons like pintrest, whatsapp, telegram, heart, email etc

Please note that while working in the development environment, it is working, but vanish completly after compiling.

Thanks you.
Manu

**Comment by stefanobartoletti** [comment]
You must add the icons that you use on the safelist, in the configuration file.

Please refer to the docs: https://bricks.stefanobartoletti.it/theme/icons/#font-awesome

**Comment by Westernwindscorp** [comment]
Thanks again.. I am really sorry that I missed that in the doc, even thought I had read most of it many times. Apologies that I am troubling you with this newbie doubts. Thanks a lot.

**Comment by stefanobartoletti** [comment]
No problem at all, I should probably add some more examples to the docs, it would probably be more immediate.

Thanks to you for your interest in Bricks ;)
