### ISSUE TITLE
Menu Drop down not working

### ISSUE THREAD

**Issue by Pauldominick** [stefanobartoletti/bricks#348]
Hi Stefano,

Thanks for the amazing theme. I am facing an issue with the dropdown for the Top Menu. I tried using a mega nav as well as the wordpress dynamic menu. In all the cases, the dropdown menu is not working. 

It was working a few months back and now i have adde with the recent version, it stopped working.

It would be great, if you can take a look at it

**Comment by stefanobartoletti** [comment]
Hi, thank you for reporting this, but I need a better report of the issue.

Please follow the guidelines of the Bug reporting template https://github.com/stefanobartoletti/bricks/issues/new?assignees=&labels=bug&template=1-bug-report.md&title= and provide more information and context.
