### ISSUE TITLE
Dropdown not working in Top Menu

### ISSUE THREAD

**Issue by Pauldominick** [stefanobartoletti/bricks#349]
### Environment

- Bricks version: 0.30.3
- WordPress version: 6.0.1
- WordPress plugins names and version: NA
- Browser:Google Chrome
- Other info: NA

### Describe the bug

An issue with the dropdown for the Top Menu. I tried using a mega navigation as well as the wordpress dynamic menu. In all the cases, the dropdown menu is not working.

It was working a few months back and now i have addeded  the recent version,(0.30.3), it stopped working.

### Steps To Reproduce
Steps to reproduce the behavior 
1. Go to Home page of the website
2. Go to the top dropdown menu in a navigation bar
3. Click on the dropdown button
4. Dropdown button not responding

### Expected behavior

When you hover over or click on the dropdown button or icon to see  the sub category and sub menu will. 

### Additional context

NA

**Comment by stefanobartoletti** [comment]
Looks like the issue was introduced by upgrading popper.js to the latest version.

I think that you can safely use bricks v.0.30.2 (the only real differences are some updates to dev dependencies, nothing that affects functionality) while I try to figure out this.

**Comment by Pauldominick** [comment]
Thanks for the update.

**Comment by stefanobartoletti** [comment]
The latest update (`v0.30.4`) should have fixed the issue.

Can you please confirm this?

**Comment by Pauldominick** [comment]
It is working as intended. Thanks for the swift reponse and resolution.

Closing this issues as it is resolved.

Thanks Again. This is a great work

**Comment by stefanobartoletti** [comment]
Thanks to you for reporting this!
