### ISSUE TITLE
Bootstrap and GooglePageSpeed

### ISSUE THREAD

**Issue by z-website** [stefanobartoletti/bricks#41]
Hello Stefano!
Does bootstrap manage to achieve 95 scores on mobile on Google PageSpeed?

**Comment by stefanobartoletti** [comment]
Hi, it really depends on your specific configuration.

Bootstrap by itself is a complete library which carries a lot of utilities and components by default.

Bricks uses Bootstrap from its sources, and is configured to use PurgeCSS by default, which optimizes your final CSS bundle to only include classes that you have actually used in your templates.

Im currently working to migrate Bricks from Bootstrap 4 to 5, where I plan to modularize even the inclusion of the JavaScript part, it should help to improve performances even more.

Said that, Bootstrap alone is not the only factor here, the final speed is also affected by images, fonts, how many extra libraries you need to use, and so on.
