### ISSUE TITLE
imagemin not working

### ISSUE THREAD

**Issue by Pauldominick** [stefanobartoletti/bricks#442]
### Environment

- Bricks version: 0.30.7
- WordPress version: 6.0
- WordPress plugins names and version: NA
- Browser: Google Chrome
- Other info: NA

### Describe the bug

The imagemin plugin stopped working and givin error while running the yarn install script.

### Expected behavior
 Should be able to complete the script run without any error.

### Additional context

Error message:

yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "stylelint-config-standard-scss > stylelint-config-recommended-scss > postcss-scss@4.0.3" has unmet peer dependency "postcss@^8.3.3".
[4/4] Building fresh packages...
[-/6] ⠁ waiting...
[-/6] ⠁ waiting...
[3/6] ⠁ gifsicle
[4/6] ⠂ mozjpeg
warning Error running install script for optional dependency: "C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\gifsicle
Output:
connect ETIMEDOUT 2405:200:1607:2820:41::36:443
gifsicle pre-build test failed
compiling from source
Error: Command failed: C:\\Windows\\system32\\cmd.exe /s /c \"autoreconf -ivf\"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

    at C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\execa\\index.js:231:11
[-/6] ⠄ waiting...
[-/6] ⠄ waiting...
[-/6] ⠄ waiting...
[4/6] ⠄ mozjpeg
warning Error running install script for optional dependency: "C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\mozjpeg: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\mozjpeg
Output:
connect ETIMEDOUT 2405:200:1607:2820:41::36:443
mozjpeg pre-build test failed
compiling from source
Error: Command failed: C:\\Windows\\system32\\cmd.exe /s /c \"autoreconf -fiv\"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

    at C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\execa\\index.js:231:11
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
warning Error running install script for optional dependency: "C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\optipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\optipng-bin
Output:
connect ETIMEDOUT 2405:200:1607:2820:41::36:443
optipng pre-build test failed
compiling from source
Error: Command failed: C:\\Windows\\system32\\cmd.exe /s /c \"./configure --with-system-zlib --prefix=\"C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\optipng-bin\\vendor\" --bindir=\"C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\optipng-bin\\vendor\"\"
'.' is not recognized as an internal or external command,
operable program or batch file.

    at C:\\xampp\\htdocs\\wolf\\wp-content\\themes\\bricks\\node_modules\\execa\\index.js:231:11
Done in 203.81s.

**Comment by stefanobartoletti** [comment]
I cannot reproduce this, everything is working fine for me.

Don't know if this could be related, but try to check read/write permissions.

**Comment by Pauldominick** [comment]
Thanks for the suggestion. Will give it a try.
