### ISSUE TITLE
Query on dropdown menu

### ISSUE THREAD

**Issue by Pauldominick** [stefanobartoletti/bricks#443]
Hi Stefano,

When an updating the dependency to   "bootstrap": "5.2.3", the dropdown and some other js feaures not working. I am not adding this an issue bug as this is somthing that I have tried and not related to the currecnt buld version.  

1. Any sugestion on why this is happening.
2. Any future upgrade to   "bootstrap": "5.2.3"

I have also raised a bug for imagemin not working
https://github.com/stefanobartoletti/bricks/issues/442#issue-1522189400

Thanks 
 Paul

**Comment by stefanobartoletti** [comment]
That version of Bootstrap is not yet integrated into this project. 

Also, this seems a bit vague, there is not much precise information or context. 

If you have already done some testing and work on it, feel free to open a PR, I accept contributions.
