### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by z-website** [stefanobartoletti/bricks#45]
Hello!
I want to install bootstrap 5 myself.

1. Replacing node_modules - bootstrap 4 with bootstrap 5
2. Removing bootstrap native
3. Updating dependencies
4. Editing php templates taking into account the new syntax.
5. Doesn't make sense in bootstrap native at the moment? Bootstrap says you don't need to use jquery, or should you block it anyway?

Or is it much more complicated?
When planning to Update?

**Comment by stefanobartoletti** [comment]
Yes, this is basically what you need to do.

I don't have an exact release date for updating to Bootstrap 5 myself, I'm working on it but this is a side project, I work on it in my spare time.

**Comment by stefanobartoletti** [comment]
The latest release updated Bootstrap to version 5.
